// Datos de proyectos (originales, sin eliminar ninguno)
const proyectosData = [
  { titulo: "Promover la producción agroecológica y el desarrollo socioeconómico a través de la actividad agropecuaria de los/las pequeños/as campesinos/as en la provincia de Montecristi, R.D.", fecha: "2025", monto: 71830, localizacion: "Provincia de Montecristi, República Dominicana", resumen: "Este proyecto tiene como objetivo fortalecer la soberanía alimentaria y la producción agroecológica de alimentos en comunidades campesinas de Montecristi. Se impulsará la producción de hortalizas, la crianza de ganado ovicaprino y la capacitación en técnicas sostenibles, contribuyendo así al desarrollo socioeconómico de las familias productoras.", entidades: '<div class="entidad-item"><img src="https://i.postimg.cc/xTbkqdVs/Logo.png" alt="CEPOCS" width="40" height="auto" loading="lazy"><span class="entidad-nombre">CEPOCS</span></div><div class="entidad-item"><img src="https://i.postimg.cc/JG4ymtv2/Manos-unidas.png" alt="Manos Unidas" width="60" height="auto" loading="lazy"><span class="entidad-nombre">Manos Unidas</span></div>' },
  { titulo: "El cacao agroecológico: instrumento de empoderamiento de la mujer y de las comunidades de la Cordillera Septentrional, RD", fecha: "2024", monto: 444617, localizacion: "Los Hidalgos, Guananico, Altamira", resumen: "Intervención en el marco de la cooperación feminista, alineada con el ODS 5. Se incluyó fortalecimiento del liderazgo feminista, puesta en funcionamiento de una Unidad de Procesamiento de Cacao gestionada por mujeres, mejora de capacidades para la comercialización y producción agrícola agroecológica.", entidades: '<div class="entidad-item"><img src="https://i.postimg.cc/xTbkqdVs/Logo.png" alt="CEPOCS" width="40" height="auto" loading="lazy"><span class="entidad-nombre">CEPOCS</span></div><div class="entidad-item aecid"><img src="https://i.postimg.cc/YS5rRHtw/AECID-HORIZONTAL-CMYK-COLOR.png" alt="AECID" width="60" height="auto" loading="lazy"><span class="entidad-nombre">AECID</span></div><div class="entidad-item prodiversa"><img src="https://i.postimg.cc/jd8tk8vJ/LOGO-PRODIVERSA-FINAL.png" alt="Prodiversa" width="60" height="auto" loading="lazy"><span class="entidad-nombre">Prodiversa</span></div>' },
  { titulo: "Producción agroecológica y participación de la mujer en comunidades marginadas. Provincia Valverde.", fecha: "2023", monto: 35542, localizacion: "Distrito Municipal de Paradero (La Cayota, El Aguacate, La Lomota)", resumen: "Proyecto socioproductivo que incrementó los ingresos de las productoras en un 25%, reduciendo la pobreza. Se fortaleció a Alcaldías Municipales y Ministerios de Agricultura y Medio Ambiente.", entidades: '<div class="entidad-item"><img src="https://i.postimg.cc/xTbkqdVs/Logo.png" alt="CEPOCS" width="40" height="auto" loading="lazy"><span class="entidad-nombre">CEPOCS</span></div><div class="entidad-item"><img src="https://i.postimg.cc/JG4ymtv2/Manos-unidas.png" alt="Manos Unidas" width="60" height="auto" loading="lazy"><span class="entidad-nombre">Manos Unidas</span></div><div class="entidad-item"><img src="https://i.postimg.cc/Pr11Ww45/Dm-PAradero.jpg" alt="Ayuntamiento Paradero" width="40" height="auto" loading="lazy"><span class="entidad-nombre">Ayuntamiento Paradero</span></div>' },
  { titulo: "Empoderamiento de las mujeres a través de la mejora de la transformación y comercialización del café en Paradero, RD", fecha: "2022", monto: 249687, localizacion: "Distrito Municipal de Paradero", resumen: "Se acompañó a las mujeres de La Cayota en su proceso de empoderamiento individual y colectivo, a través de la creación de un centro de transformación y comercialización del café.", entidades: '<div class="entidad-item"><img src="https://i.postimg.cc/xTbkqdVs/Logo.png" alt="CEPOCS" width="40" height="auto" loading="lazy"><span class="entidad-nombre">CEPOCS</span></div><div class="entidad-item aecid"><img src="https://i.postimg.cc/YS5rRHtw/AECID-HORIZONTAL-CMYK-COLOR.png" alt="AECID" width="60" height="auto" loading="lazy"><span class="entidad-nombre">AECID</span></div><div class="entidad-item prodiversa"><img src="https://i.postimg.cc/jd8tk8vJ/LOGO-PRODIVERSA-FINAL.png" alt="Prodiversa" width="60" height="auto" loading="lazy"><span class="entidad-nombre">Prodiversa</span></div><div class="entidad-item"><img src="https://i.postimg.cc/Pr11Ww45/Dm-PAradero.jpg" alt="Ayuntamiento Paradero" width="40" height="auto" loading="lazy"><span class="entidad-nombre">Ayuntamiento Paradero</span></div>' },
  { titulo: "Intercambio entre Alcaldías Municipales España/República Dominicana", fecha: "2022", monto: 9500, localizacion: "Madrid; Andalucía; Castilla la Mancha (España)", resumen: "Alcaldes, director de Mancomunidad y representantes de la sociedad civil dominicana visitaron España para reunirse con representantes políticos y sociales.", entidades: '<div class="entidad-item"><img src="https://i.postimg.cc/xTbkqdVs/Logo.png" alt="CEPOCS" width="40" height="auto" loading="lazy"><span class="entidad-nombre">CEPOCS</span></div><div class="entidad-item prodiversa"><img src="https://i.postimg.cc/jd8tk8vJ/LOGO-PRODIVERSA-FINAL.png" alt="Prodiversa" width="60" height="auto" loading="lazy"><span class="entidad-nombre">Prodiversa</span></div><div class="entidad-item"><img src="https://i.postimg.cc/wTDDXmVM/Gobierno-de-Rep-Dominicana-(cropped).png" alt="Mancomunidad" width="50" height="auto" loading="lazy"><span class="entidad-nombre">Mancomunidad</span></div>' },
  { titulo: "Aumentar la productividad y los ingresos agrícolas con enfoque agroecológico", fecha: "2020", monto: 217315, localizacion: "Esperanza, Altamira, Navarrete", resumen: "Se contribuyó al desarrollo económico mediante el aumento de la productividad de familias agrícolas. Se incluyó capacitación técnica y fábrica de zumos y mermeladas gestionada por mujeres rurales.", entidades: '<div class="entidad-item"><img src="https://i.postimg.cc/xTbkqdVs/Logo.png" alt="CEPOCS" width="40" height="auto" loading="lazy"><span class="entidad-nombre">CEPOCS</span></div><div class="entidad-item aecid"><img src="https://i.postimg.cc/YS5rRHtw/AECID-HORIZONTAL-CMYK-COLOR.png" alt="AECID" width="60" height="auto" loading="lazy"><span class="entidad-nombre">AECID</span></div><div class="entidad-item prodiversa"><img src="https://i.postimg.cc/jd8tk8vJ/LOGO-PRODIVERSA-FINAL.png" alt="Prodiversa" width="60" height="auto" loading="lazy"><span class="entidad-nombre">Prodiversa</span></div><div class="entidad-item"><img src="https://i.postimg.cc/Pr11Ww45/Dm-PAradero.jpg" alt="Ayuntamiento Paradero" width="40" height="auto" loading="lazy"><span class="entidad-nombre">Ayuntamiento Paradero</span></div>' },
  { titulo: "Gestión de Residuos Sólidos en 9 municipios y 12 Distritos", fecha: "2021", monto: 56000, localizacion: "Navarrete, Villa González, Guananíco, Esperanza, Los Hidalgos, Villa Isabela, Luperón, Imbert, Altamira", resumen: "Se contribuyó al derecho a vivir en un ambiente sano, planificando e implementando la mejora de la Política de Gestión de Residuos Sólidos.", entidades: '<div class="entidad-item"><img src="https://i.postimg.cc/xTbkqdVs/Logo.png" alt="CEPOCS" width="40" height="auto" loading="lazy"><span class="entidad-nombre">CEPOCS</span></div><div class="entidad-item"><img src="https://i.postimg.cc/wTDDXmVM/Gobierno-de-Rep-Dominicana-(cropped).png" alt="Mancomunidad" width="50" height="auto" loading="lazy"><span class="entidad-nombre">Mancomunidad</span></div>' },
  { titulo: "Aumento de la productividad del cacao y mejora de las plantaciones", fecha: "2020", monto: 110000, localizacion: "Navarrete", resumen: "Se contribuyó al desarrollo organizacional de los productores. Gran resultado: constitución de la marca, fábrica y empresa 'Chocolala'.", entidades: '<div class="entidad-item"><img src="https://i.postimg.cc/xTbkqdVs/Logo.png" alt="CEPOCS" width="40" height="auto" loading="lazy"><span class="entidad-nombre">CEPOCS</span></div><div class="entidad-item bid"><img src="https://i.postimg.cc/D8yWFmRK/Logo-BID-Espanol.png" alt="BID" width="70" height="auto" loading="lazy"><span class="entidad-nombre">BID</span></div><div class="entidad-item"><img src="https://i.postimg.cc/4ymc14wd/logo-cnc-web-2line-scaled-(1).png" alt="CNC" width="50" height="auto" loading="lazy"><span class="entidad-nombre">CNC</span></div>' }
];

// Ordenar proyectos: fecha descendente, luego monto descendente
proyectosData.sort((a,b) => {
  if (a.fecha !== b.fecha) return b.fecha - a.fecha;
  return b.monto - a.monto;
});

// Videos (9 en total)
const videosData = [
  { url: "https://www.youtube.com/watch?v=4Ph5ZhSizh8", titulo: "FEMUCOS muestra preocupación por aumento en muertes de mujeres", fecha: "2026" },
  { url: "https://www.youtube.com/shorts/kCRBCTF6XY4", titulo: "Café Paradero", fecha: "2025" },
  { url: "https://youtube.com/shorts/UKU0S8u2ruE?si=26pZkpt7w_g2Qp_Q", titulo: "Más independiente", fecha: "2026" },
  { url: "https://www.youtube.com/embed/K8IXvDBhaPI", titulo: "Mujeres de la costa de Montecristi beneficiadas con el proyecto CEPOCS y Manos Unidas", fecha: "2026" },
  { url: "https://www.youtube.com/embed/lKwXbkYBCCc", titulo: "Cierre proyecto ejecutado por CEPOCS, beneficiaria FEMUCOS, financiado por fondos Canadá", fecha: "2026" },
  { url: "https://www.youtube.com/embed/zExraq8ixHY", titulo: "Proyecto CEPOCS - 15 de diciembre de 2025", fecha: "2025" },
  { url: "https://www.youtube.com/embed/rc-8jl9uvOI", titulo: "Proyecto fondo Canadá, ejecutado por CEPOCS, beneficiaria FEMUCOS. Cordillera Septentrional", fecha: "2026" },
  { url: "https://www.youtube.com/embed/C9UHnD88mFw", titulo: "Oficina provincial Valverde de Medio Ambiente, dio inicio a la amplia jornada", fecha: "2024" },
  { url: "https://www.youtube.com/embed/CZwkFqQhOZU", titulo: "CEPOCS, FEMUCOS y AMNA abren oficinas en Navarrete", fecha: "2026" }
];
videosData.sort((a,b) => b.fecha - a.fecha);

// Fotos (28)
const fotosBase = [
  { src: "https://i.postimg.cc/zDHRSgjS/IMG-20230418-151548891.jpg", alt: "Actividad CEPOCS" },
  { src: "https://i.postimg.cc/yYPmwNKv/Captura-de-pantalla-2026-05-22-235256.png", alt: "Captura de pantalla proyecto CEPOCS" },
  { src: "
